import { readFileSync, writeFileSync, existsSync } from "fs";
import { dirname, resolve } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "../..");
const envPath = resolve(root, ".env");
const outPath = resolve(root, "src/kakeibo/runtimeAuthConfig.js");

let clientId = process.env.GOOGLE_CLIENT_ID || "";

if (!clientId && existsSync(envPath)) {
  const env = readFileSync(envPath, "utf8");
  for (const line of env.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1).trim();
    if (key === "GOOGLE_CLIENT_ID") {
      clientId = value;
      break;
    }
  }
}

const contents = `// Generated by tools/kakeibo/syncAuthConfig.js — do not edit by hand.
export const GOOGLE_CLIENT_ID = ${JSON.stringify(clientId)};
`;

writeFileSync(outPath, contents);
console.log(`Wrote ${outPath}${clientId ? "" : " (GOOGLE_CLIENT_ID is empty — login will be disabled)"}`);
